apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibankingpvc
spec:
  storageClassName: ibankingstorageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
